[package]
name = "rugo"
version = "0.1.0"
authors = ["Serbe <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
postgres = "0.15"
r2d2 = "0.8"
r2d2_postgres = "0.14"
futures = "0.1"
# serde = "1.0"
# serde_derive = "1.0"
serde_json = "1.0"
# uuid = "0.7"
actix-rt = "0.2"

# [dependencies.actix]
# version = "0.7"
# features = ["rust-tls"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.repdb]
version = "*"
path = "repdb"
