[package]
name = "rugo"
version = "0.5.1"
authors = ["Serbe <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
# anyhow = "1.0"
# base64 = "0.11"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.7"
postgres = { version = "0.15", features = ["with-chrono"] }
r2d2 = "0.8"
r2d2_postgres = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ws = "0.9"
# bincode = "1.2"
# futures = "0.1"
