[package]
authors = ["Serbe <mkoctuk@gmail.com>"]
edition = "2018"
name = "rugo"
version = "0.8.5"

[dependencies]
actix = "0.9"
actix-cors = "0.2"
actix-rt = "1.1"
actix-web = "2.0"
actix-web-actors = "2.0"
deadpool-postgres = "0.5"
dotenv = "0.15"
env_logger = "0.7"
futures = "0.3"
log = {version = "0.4", features = ["std"]}
once_cell = "1.4"
rand = "0.7"
rpel = {git = "https://github.com/serbe/rpel", version = "0.3.3"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
