[package]
name = "rugo"
version = "0.5.1"
authors = ["Serbe <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.9"
actix-identity = "0.2"
actix-rt = "1.0.0"
actix-web = "2.0"
actix-web-actors = "2.0"
base64 = "0.11"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.7"
futures = "0.3"
# postgres = { version = "0.17", features = ["with-chrono-0_4"] }
# r2d2 = "0.8"
# r2d2_postgres = "0.16"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rpel = { git = "https://github.com/serbe/rpel", version = "0.1.2" }