[package]
name = "rugo"
version = "0.4.0"
authors = ["Serbe <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
actix-identity = "0.1"
actix-rt = "0.2"
actix-service = "0.4"
actix-session = "0.2"
actix-web = "1.0"
base64 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.14"
env_logger = "0.6"
futures = "0.1"
postgres = { version = "0.15", features = ["with-chrono"] }
r2d2 = "0.8"
r2d2_postgres = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
